version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: movie_app
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"   # Apache
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: movie_app
      MYSQL_USER: movie_app
      MYSQL_PASSWORD: password
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: movie_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: movie_app
      MYSQL_USER: movie_app
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8081:8080" # Adminer accessible on port 8081
    depends_on:
      - db

volumes:
  db_data:
